"""
make_ui_images.py - Packs the three 128x128 test images into ui/images.js so the
web interface works offline, even when index.html is opened straight from disk.
Run from the project root:   python python/make_ui_images.py
"""
import base64, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = ["cameraman", "coins", "shapes"]
lines = ["// Generated by python/make_ui_images.py - 128x128 grayscale test images.",
         "window.TEST_IMAGES = {"]
for n in names:
    with open(os.path.join(ROOT, "images", "original", f"{n}.png"), "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    lines.append(f'  {n}: "data:image/png;base64,{b64}",')
lines.append("};")
with open(os.path.join(ROOT, "ui", "images.js"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote ui/images.js")
